### PR TITLE
Support gTTS for better speech & add a feature flag for Heard

### PR DESCRIPTION
**Pull request by skeenan947**
Love your project, thanks for putting this together!
I've added a couple of optional features, let me know what you think.  Happy to modify however you'd like.
* Use of the gTTS library - the pyttsx3 engine is nice as it all runs offline, but gTTS doesn't add much delay (if any), and the node needs to run online to get to OpenAI anyways, so this seemed like the best choice.  it's also a free API.
* I didn't like having to hear the "Heard" repeated back to me all the time, so I added a feature flag to disable this.

Thank you!

### CODE REVIEW

**Review by judahpaul16 — CHANGES_REQUESTED** [review]
Great work but you may need to tweak the prompt slightly. Here's the response I got to "how's it going" from claude-3.5-sonnet.
image
You can try to tweak the samples in the `src/routes.py` file to get the action router to route better too.

**Comment by skeenan947** [comment]
GPT-4o was doing that, thought I nipped that one in the bud w/ this round.  Thanks!  I'll adjust.
I may also push an update to put this in settings as well instead of env vars if you'd prefer.

**Comment by judahpaul16** [comment]
> GPT-4o was doing that, thought I nipped that one in the bud w/ this round. Thanks! I'll adjust. I may also push an update to put this in settings as well instead of env vars if you'd prefer.

That works.

**Comment by skeenan947** [comment]
I can't seem to reproduce the issue, oddly.  Do you have any custom instruction set?  I'm using Claude 3.5 sonnet w/ no custom instruction and it's responding correctly.

**Comment by skeenan947** [comment]
Pulled in the rest of my updates, let me know what you think!  and if you run into that issue again; hoping my latest prompt update fixes that.  Still not sure why the router is directing "how's it going" to weather though.

**Comment by skeenan947** [comment]
ah it looks like you have react's build checked in too, I'll update that shortly

**Comment by skeenan947** [comment]
using a larger embeddings model fixes the route issue

**Comment by judahpaul16** [comment]
Great work! Thank you for your contribution!

image

**Pull request merged**
